version: '3.8'
services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - catalogdbdata:/data/db

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
    
  discount:
    container_name: discountdb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - discountdbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Password12*
      - POSTGRES_DB=discountdb

  identitydb:
    container_name: identitydb
    restart: always
    cap_add: [ 'SYS_PTRACE' ]
    ports:
      - "1433:1433"
    volumes:
      - identitydbdata:/var/opt/mssql
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=Password12*

  orderdb:
    container_name: orderdb
    restart: always
    cap_add: [ 'SYS_PTRACE' ]
    ports:
      - "1444:1433"
    volumes:
      - orderdbdata:/var/opt/mssql
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=Password12*
  
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12.4-management
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"


  catalog.api:
    image: catalog_api_image
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=DEVELOPMENT
      - RabbitMQUrl=rabbitmq
      - IdentityServerUrl=http://identityserver.api
      - DatabaseSettings:ConnectionString=mongodb://catalogdb:27017
    ports:
      - "5011:80"
    depends_on:
      - catalogdb
      # - rabbitmq
      - identityserver.api


  identityserver.api:
    image: identityserver_api_image
    container_name: identityserver.api
    environment:
      - ASPNETCORE_ENVIRONMENT=DEVELOPMENT
      - "ConnectionStrings:DefaultConnection=Server=identitydb,1433;Database=IdentityDb;User Id=sa;Password=Password12*;"
    ports:
      - "5001:80"
    depends_on:
      - identitydb


